#!/bin/bash

function USAGE
{
	echo "Usage: ssng {start|stop} src-path dst-path" >&2
}

if [ "$#" -ne "3" ]; then
    USAGE
    exit 1
fi

SPOOL_BASE="/var/spool/synchro-seedbox-ng"
SRC_PATH=$2
DST_PATH=$3
SYNC_ID=`echo -n $2 | md5sum | cut -d' ' -f 1`
SYNC_SPOOL_SRC_PATH="$SPOOL_BASE/$SYNC_ID"
SYNC_FILELIST="$SYNC_SPOOL_SRC_PATH/file_list.log"
SYNC_LOG="$SYNC_SPOOL_SRC_PATH/sending.log"
LOCK_FILE="$SYNC_SPOOL_SRC_PATH/lock"

function browse_dir
{
local dir
local rel
local age
local i

if test $# -lt 1
then
dir=$SRC_PATH
rel=""
else
rel="$1/"
dir="$SRC_PATH$rel"
fi

echo "scanning $dir"

for i in "$dir"*
do
	if test -f "$i"
	then

		age=`stat -c %Y "$i"`
		echo "$age:${i//"$SRC_PATH/"/}" >> $SYNC_FILELIST
	else
	if test -d "$i"
	then
		browse_dir "${i//"$SRC_PATH"/}"
	fi
	fi
done

#Delete empty folder
rmdir "$dir/"* 2> /dev/null 
}

function update_list
{
	rm $SYNC_FILELIST 2> /dev/null
	browse_dir
}

function send_files
{
patern='*[0-9]:'
patern2='/*'

old_IFS=$IFS
IFS=$'\n'
for line in $(sort $SYNC_FILELIST)
do
	IFS=$old_IFS
	line1=${line##$patern}
#	echo $line1
	fic=${line1##"$SRC_PATH"}
#	echo $fic
	rel="${fic%$patern2}/"
#	echo $rel
	send_file_job "$line1"
	update_list
done
IFS=$old_IFS
}

function send_file_job
{
	echo "sending $1"
	echo "$1" > $SYNC_LOG
	
        rsync -aPRL --partial-dir='.tmp' --temp-dir='.tmp' --rsh=ssh --remove-sent-files --bwlimit=$bwlimit "$1" "$user_SSH"@"$IP":"$DST_PATH" >> $SYNC_LOG
}

. /usr/local/etc/synchro-seedbox-ng/synchro.conf

case "$1" in
	start)

		if test -f $LOCK_FILE
		then
			echo -e "Sync of $2 folder is already running"
			exit 3
		else
			if [ ! -d "$SYNC_SPOOL_SRC_PATH" ]; then
				mkdir $SYNC_SPOOL_SRC_PATH
			fi
			touch $LOCK_FILE
		fi

		update_list

		while test -f $SYNC_FILELIST
		do
			cd $SRC_PATH
			send_files
		done

		rm $LOCK_FILE
	;;
	stop)
		echo "not implemented yet"
	;;
	*)
		USAGE
        	exit 3
        ;;
esac
